---
- name: Install Helm on Ubuntu
  hosts: localhost
  gather_facts: yes
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - curl
          - apt-transport-https
          - software-properties-common
        state: present

    - name: Add Helm GPG key
      shell: |
        curl -fsSL https://baltocdn.com/helm/signing.asc | sudo apt-key add -
      become_user: root

    - name: Add Helm APT repository
      apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present
      become_user: root

    - name: Update APT cache
      apt:
        update_cache: yes
      become_user: root

    - name: Install Helm
      apt:
        name: helm
        state: present
      become_user: root

    - name: Verify Helm installation
      command: helm version --short
      register: helm_version

    - name: Display Helm version
      debug:
        var: helm_version.stdout_lines
